"""Prompt templates for all dev-team agents."""

from prompts.architect import ARCHITECT_DEV_REVIEW_SYSTEM_PROMPT, ARCHITECT_RESEARCH_CONTEXT, ARCHITECT_SYSTEM_PROMPT, ARCHITECT_USER_PROMPT
from prompts.research import RESEARCH_SYSTEM_PROMPT, RESEARCH_USER_PROMPT
from prompts.pm_analysis import PM_ANALYSIS_SYSTEM_PROMPT, PM_ANALYSIS_USER_PROMPT_HEADER
from prompts.ci import COMMIT_SYSTEM_PROMPT, COMMIT_USER_PROMPT
from prompts.dashboard_builder import DASHBOARD_BUILDER_SYSTEM_PROMPT
from prompts.developer import DEVELOPER_SYSTEM_PROMPT
from prompts.etl_porter import ETL_PORTER_SYSTEM_PROMPT
from prompts.pipeline_builder import PIPELINE_BUILDER_SYSTEM_PROMPT
from prompts.pm import (
    PM_ARCHITECT_REVIEW,
    PM_ARCHITECT_SUBTASKS_HEADER,
    PM_ARCHITECT_USER_PROMPT,
    PM_DEVELOPER_REVIEW,
    PM_DEVELOPER_USER_PROMPT,
    PM_TESTING_REVIEW,
    PM_TESTING_USER_PROMPT,
    PM_USER_STORY_SYSTEM_PROMPT,
)
from prompts.review_engine import REVIEW_ENGINE_SYSTEM_PROMPT
from prompts.reviewer import REVIEWER_SYSTEM_PROMPT, REVIEWER_USER_PROMPT_HEADER
from prompts.staging import STAGING_INSTRUCTION
from prompts.tester import (
    TESTER_AGENT_SYSTEM_PROMPT,
    TESTER_CI_SYSTEM_PROMPT,
    TESTER_FIX_SYSTEM_PROMPT,
    TESTER_FIX_USER_PROMPT,
    TESTER_INTEGRATION_SYSTEM_PROMPT,
    TESTER_ROLE_SYSTEM_PROMPT,
    TESTER_USER_PROMPT_FOOTER,
    TESTER_USER_PROMPT_HEADER,
)
from prompts.vision_embedding import VISION_EMBEDDING_SYSTEM_PROMPT

__all__ = [
    "ARCHITECT_DEV_REVIEW_SYSTEM_PROMPT",
    "ARCHITECT_RESEARCH_CONTEXT",
    "RESEARCH_SYSTEM_PROMPT",
    "RESEARCH_USER_PROMPT",
    "PM_ANALYSIS_SYSTEM_PROMPT",
    "PM_ANALYSIS_USER_PROMPT_HEADER",
    "ARCHITECT_SYSTEM_PROMPT",
    "ARCHITECT_USER_PROMPT",
    "COMMIT_SYSTEM_PROMPT",
    "COMMIT_USER_PROMPT",
    "DASHBOARD_BUILDER_SYSTEM_PROMPT",
    "DEVELOPER_SYSTEM_PROMPT",
    "ETL_PORTER_SYSTEM_PROMPT",
    "PIPELINE_BUILDER_SYSTEM_PROMPT",
    "PM_ARCHITECT_REVIEW",
    "PM_ARCHITECT_SUBTASKS_HEADER",
    "PM_ARCHITECT_USER_PROMPT",
    "PM_DEVELOPER_REVIEW",
    "PM_DEVELOPER_USER_PROMPT",
    "PM_TESTING_REVIEW",
    "PM_TESTING_USER_PROMPT",
    "PM_USER_STORY_SYSTEM_PROMPT",
    "REVIEW_ENGINE_SYSTEM_PROMPT",
    "REVIEWER_SYSTEM_PROMPT",
    "REVIEWER_USER_PROMPT_HEADER",
    "STAGING_INSTRUCTION",
    "TESTER_AGENT_SYSTEM_PROMPT",
    "TESTER_CI_SYSTEM_PROMPT",
    "TESTER_FIX_SYSTEM_PROMPT",
    "TESTER_FIX_USER_PROMPT",
    "TESTER_INTEGRATION_SYSTEM_PROMPT",
    "TESTER_ROLE_SYSTEM_PROMPT",
    "TESTER_USER_PROMPT_FOOTER",
    "TESTER_USER_PROMPT_HEADER",
    "VISION_EMBEDDING_SYSTEM_PROMPT",
]
